/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated/wishlist'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedAddressesRouteImport } from './routes/_authenticated/addresses'
import { Route as AuthenticatedAccountEditRouteImport } from './routes/_authenticated/account-edit'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as CategorySlugIndexRouteImport } from './routes/category.$slug.index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as CategorySlugSubRouteImport } from './routes/category.$slug.$sub'
import { Route as ApiPublicAdminBulkLinkImagesRouteImport } from './routes/api/public/admin-bulk-link-images'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminScanRouteImport } from './routes/_authenticated/admin/scan'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminPipeline_upscaleRouteImport } from './routes/_authenticated/admin/pipeline_upscale'
import { Route as AuthenticatedAdminInventoryRouteImport } from './routes/_authenticated/admin/inventory'
import { Route as AuthenticatedAdminImageQualityPreviewRouteImport } from './routes/_authenticated/admin/image-quality-preview'
import { Route as AuthenticatedAdminImageBackfillRouteImport } from './routes/_authenticated/admin/image-backfill'
import { Route as AuthenticatedAdminHomepageFeaturedRouteImport } from './routes/_authenticated/admin/homepage-featured'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminProductsIndexRouteImport } from './routes/_authenticated/admin/products.index'
import { Route as AuthenticatedAdminOrdersIndexRouteImport } from './routes/_authenticated/admin/orders.index'
import { Route as ApiPublicHooksLowStockDigestRouteImport } from './routes/api/public/hooks/low-stock-digest'
import { Route as AuthenticatedAdminProductsIdRouteImport } from './routes/_authenticated/admin/products.$id'
import { Route as AuthenticatedAdminOrdersIdRouteImport } from './routes/_authenticated/admin/orders.$id'
import { Route as AuthenticatedAdminInventoryImportRouteImport } from './routes/_authenticated/admin/inventory.import'
import { Route as AuthenticatedAdminInventoryAuditRouteImport } from './routes/_authenticated/admin/inventory.audit'
import { Route as AuthenticatedAdminInventoryIdRouteImport } from './routes/_authenticated/admin/inventory.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAddressesRoute = AuthenticatedAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountEditRoute =
  AuthenticatedAccountEditRouteImport.update({
    id: '/account-edit',
    path: '/account-edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CategorySlugIndexRoute = CategorySlugIndexRouteImport.update({
  id: '/category/$slug/',
  path: '/category/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const CategorySlugSubRoute = CategorySlugSubRouteImport.update({
  id: '/category/$slug/$sub',
  path: '/category/$slug/$sub',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminBulkLinkImagesRoute =
  ApiPublicAdminBulkLinkImagesRouteImport.update({
    id: '/api/public/admin-bulk-link-images',
    path: '/api/public/admin-bulk-link-images',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/admin/users.lazy').then((d) => d.Route),
)
const AuthenticatedAdminScanRoute = AuthenticatedAdminScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/admin/scan.lazy').then((d) => d.Route),
)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPipeline_upscaleRoute =
  AuthenticatedAdminPipeline_upscaleRouteImport.update({
    id: '/pipeline_upscale',
    path: '/pipeline_upscale',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInventoryRoute =
  AuthenticatedAdminInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/inventory.lazy').then((d) => d.Route),
  )
const AuthenticatedAdminImageQualityPreviewRoute =
  AuthenticatedAdminImageQualityPreviewRouteImport.update({
    id: '/image-quality-preview',
    path: '/image-quality-preview',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminImageBackfillRoute =
  AuthenticatedAdminImageBackfillRouteImport.update({
    id: '/image-backfill',
    path: '/image-backfill',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHomepageFeaturedRoute =
  AuthenticatedAdminHomepageFeaturedRouteImport.update({
    id: '/homepage-featured',
    path: '/homepage-featured',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/categories.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedAdminProductsIndexRoute =
  AuthenticatedAdminProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminProductsRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/products.index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedAdminOrdersIndexRoute =
  AuthenticatedAdminOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/orders.index.lazy').then(
      (d) => d.Route,
    ),
  )
const ApiPublicHooksLowStockDigestRoute =
  ApiPublicHooksLowStockDigestRouteImport.update({
    id: '/api/public/hooks/low-stock-digest',
    path: '/api/public/hooks/low-stock-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminProductsIdRoute =
  AuthenticatedAdminProductsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminProductsRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/products.$id.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedAdminOrdersIdRoute =
  AuthenticatedAdminOrdersIdRouteImport.update({
    id: '/orders/$id',
    path: '/orders/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInventoryImportRoute =
  AuthenticatedAdminInventoryImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminInventoryRoute,
  } as any)
const AuthenticatedAdminInventoryAuditRoute =
  AuthenticatedAdminInventoryAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedAdminInventoryRoute,
  } as any)
const AuthenticatedAdminInventoryIdRoute =
  AuthenticatedAdminInventoryIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminInventoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/account-edit': typeof AuthenticatedAccountEditRoute
  '/addresses': typeof AuthenticatedAddressesRoute
  '/cart': typeof AuthenticatedCartRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/homepage-featured': typeof AuthenticatedAdminHomepageFeaturedRoute
  '/admin/image-backfill': typeof AuthenticatedAdminImageBackfillRoute
  '/admin/image-quality-preview': typeof AuthenticatedAdminImageQualityPreviewRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRouteWithChildren
  '/admin/pipeline_upscale': typeof AuthenticatedAdminPipeline_upscaleRoute
  '/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/scan': typeof AuthenticatedAdminScanRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/api/public/admin-bulk-link-images': typeof ApiPublicAdminBulkLinkImagesRoute
  '/category/$slug/$sub': typeof CategorySlugSubRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/category/$slug/': typeof CategorySlugIndexRoute
  '/admin/inventory/$id': typeof AuthenticatedAdminInventoryIdRoute
  '/admin/inventory/audit': typeof AuthenticatedAdminInventoryAuditRoute
  '/admin/inventory/import': typeof AuthenticatedAdminInventoryImportRoute
  '/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/api/public/hooks/low-stock-digest': typeof ApiPublicHooksLowStockDigestRoute
  '/admin/orders/': typeof AuthenticatedAdminOrdersIndexRoute
  '/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/account-edit': typeof AuthenticatedAccountEditRoute
  '/addresses': typeof AuthenticatedAddressesRoute
  '/cart': typeof AuthenticatedCartRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/blog': typeof BlogIndexRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/homepage-featured': typeof AuthenticatedAdminHomepageFeaturedRoute
  '/admin/image-backfill': typeof AuthenticatedAdminImageBackfillRoute
  '/admin/image-quality-preview': typeof AuthenticatedAdminImageQualityPreviewRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRouteWithChildren
  '/admin/pipeline_upscale': typeof AuthenticatedAdminPipeline_upscaleRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/scan': typeof AuthenticatedAdminScanRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/api/public/admin-bulk-link-images': typeof ApiPublicAdminBulkLinkImagesRoute
  '/category/$slug/$sub': typeof CategorySlugSubRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/category/$slug': typeof CategorySlugIndexRoute
  '/admin/inventory/$id': typeof AuthenticatedAdminInventoryIdRoute
  '/admin/inventory/audit': typeof AuthenticatedAdminInventoryAuditRoute
  '/admin/inventory/import': typeof AuthenticatedAdminInventoryImportRoute
  '/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/api/public/hooks/low-stock-digest': typeof ApiPublicHooksLowStockDigestRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersIndexRoute
  '/admin/products': typeof AuthenticatedAdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/account-edit': typeof AuthenticatedAccountEditRoute
  '/_authenticated/addresses': typeof AuthenticatedAddressesRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/homepage-featured': typeof AuthenticatedAdminHomepageFeaturedRoute
  '/_authenticated/admin/image-backfill': typeof AuthenticatedAdminImageBackfillRoute
  '/_authenticated/admin/image-quality-preview': typeof AuthenticatedAdminImageQualityPreviewRoute
  '/_authenticated/admin/inventory': typeof AuthenticatedAdminInventoryRouteWithChildren
  '/_authenticated/admin/pipeline_upscale': typeof AuthenticatedAdminPipeline_upscaleRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/scan': typeof AuthenticatedAdminScanRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/api/public/admin-bulk-link-images': typeof ApiPublicAdminBulkLinkImagesRoute
  '/category/$slug/$sub': typeof CategorySlugSubRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/category/$slug/': typeof CategorySlugIndexRoute
  '/_authenticated/admin/inventory/$id': typeof AuthenticatedAdminInventoryIdRoute
  '/_authenticated/admin/inventory/audit': typeof AuthenticatedAdminInventoryAuditRoute
  '/_authenticated/admin/inventory/import': typeof AuthenticatedAdminInventoryImportRoute
  '/_authenticated/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/_authenticated/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/api/public/hooks/low-stock-digest': typeof ApiPublicHooksLowStockDigestRoute
  '/_authenticated/admin/orders/': typeof AuthenticatedAdminOrdersIndexRoute
  '/_authenticated/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/catalogue'
    | '/contact'
    | '/notifications'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/account'
    | '/account-edit'
    | '/addresses'
    | '/cart'
    | '/change-password'
    | '/checkout'
    | '/wishlist'
    | '/blog/$slug'
    | '/product/$slug'
    | '/blog/'
    | '/admin/categories'
    | '/admin/homepage-featured'
    | '/admin/image-backfill'
    | '/admin/image-quality-preview'
    | '/admin/inventory'
    | '/admin/pipeline_upscale'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/scan'
    | '/admin/users'
    | '/orders/$id'
    | '/api/public/admin-bulk-link-images'
    | '/category/$slug/$sub'
    | '/admin/'
    | '/orders/'
    | '/category/$slug/'
    | '/admin/inventory/$id'
    | '/admin/inventory/audit'
    | '/admin/inventory/import'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/api/public/hooks/low-stock-digest'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/catalogue'
    | '/contact'
    | '/notifications'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/account'
    | '/account-edit'
    | '/addresses'
    | '/cart'
    | '/change-password'
    | '/checkout'
    | '/wishlist'
    | '/blog/$slug'
    | '/product/$slug'
    | '/blog'
    | '/admin/categories'
    | '/admin/homepage-featured'
    | '/admin/image-backfill'
    | '/admin/image-quality-preview'
    | '/admin/inventory'
    | '/admin/pipeline_upscale'
    | '/admin/reports'
    | '/admin/scan'
    | '/admin/users'
    | '/orders/$id'
    | '/api/public/admin-bulk-link-images'
    | '/category/$slug/$sub'
    | '/admin'
    | '/orders'
    | '/category/$slug'
    | '/admin/inventory/$id'
    | '/admin/inventory/audit'
    | '/admin/inventory/import'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/api/public/hooks/low-stock-digest'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/auth-callback'
    | '/catalogue'
    | '/contact'
    | '/notifications'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/account'
    | '/_authenticated/account-edit'
    | '/_authenticated/addresses'
    | '/_authenticated/cart'
    | '/_authenticated/change-password'
    | '/_authenticated/checkout'
    | '/_authenticated/wishlist'
    | '/blog/$slug'
    | '/product/$slug'
    | '/blog/'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/homepage-featured'
    | '/_authenticated/admin/image-backfill'
    | '/_authenticated/admin/image-quality-preview'
    | '/_authenticated/admin/inventory'
    | '/_authenticated/admin/pipeline_upscale'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/scan'
    | '/_authenticated/admin/users'
    | '/_authenticated/orders/$id'
    | '/api/public/admin-bulk-link-images'
    | '/category/$slug/$sub'
    | '/_authenticated/admin/'
    | '/_authenticated/orders/'
    | '/category/$slug/'
    | '/_authenticated/admin/inventory/$id'
    | '/_authenticated/admin/inventory/audit'
    | '/_authenticated/admin/inventory/import'
    | '/_authenticated/admin/orders/$id'
    | '/_authenticated/admin/products/$id'
    | '/api/public/hooks/low-stock-digest'
    | '/_authenticated/admin/orders/'
    | '/_authenticated/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CatalogueRoute: typeof CatalogueRoute
  ContactRoute: typeof ContactRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicAdminBulkLinkImagesRoute: typeof ApiPublicAdminBulkLinkImagesRoute
  CategorySlugSubRoute: typeof CategorySlugSubRoute
  CategorySlugIndexRoute: typeof CategorySlugIndexRoute
  ApiPublicHooksLowStockDigestRoute: typeof ApiPublicHooksLowStockDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/addresses': {
      id: '/_authenticated/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AuthenticatedAddressesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account-edit': {
      id: '/_authenticated/account-edit'
      path: '/account-edit'
      fullPath: '/account-edit'
      preLoaderRoute: typeof AuthenticatedAccountEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/category/$slug/': {
      id: '/category/$slug/'
      path: '/category/$slug'
      fullPath: '/category/$slug/'
      preLoaderRoute: typeof CategorySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/category/$slug/$sub': {
      id: '/category/$slug/$sub'
      path: '/category/$slug/$sub'
      fullPath: '/category/$slug/$sub'
      preLoaderRoute: typeof CategorySlugSubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-bulk-link-images': {
      id: '/api/public/admin-bulk-link-images'
      path: '/api/public/admin-bulk-link-images'
      fullPath: '/api/public/admin-bulk-link-images'
      preLoaderRoute: typeof ApiPublicAdminBulkLinkImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/scan': {
      id: '/_authenticated/admin/scan'
      path: '/scan'
      fullPath: '/admin/scan'
      preLoaderRoute: typeof AuthenticatedAdminScanRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pipeline_upscale': {
      id: '/_authenticated/admin/pipeline_upscale'
      path: '/pipeline_upscale'
      fullPath: '/admin/pipeline_upscale'
      preLoaderRoute: typeof AuthenticatedAdminPipeline_upscaleRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/inventory': {
      id: '/_authenticated/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AuthenticatedAdminInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/image-quality-preview': {
      id: '/_authenticated/admin/image-quality-preview'
      path: '/image-quality-preview'
      fullPath: '/admin/image-quality-preview'
      preLoaderRoute: typeof AuthenticatedAdminImageQualityPreviewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/image-backfill': {
      id: '/_authenticated/admin/image-backfill'
      path: '/image-backfill'
      fullPath: '/admin/image-backfill'
      preLoaderRoute: typeof AuthenticatedAdminImageBackfillRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/homepage-featured': {
      id: '/_authenticated/admin/homepage-featured'
      path: '/homepage-featured'
      fullPath: '/admin/homepage-featured'
      preLoaderRoute: typeof AuthenticatedAdminHomepageFeaturedRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products/': {
      id: '/_authenticated/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthenticatedAdminProductsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminProductsRoute
    }
    '/_authenticated/admin/orders/': {
      id: '/_authenticated/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AuthenticatedAdminOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/hooks/low-stock-digest': {
      id: '/api/public/hooks/low-stock-digest'
      path: '/api/public/hooks/low-stock-digest'
      fullPath: '/api/public/hooks/low-stock-digest'
      preLoaderRoute: typeof ApiPublicHooksLowStockDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/products/$id': {
      id: '/_authenticated/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AuthenticatedAdminProductsIdRouteImport
      parentRoute: typeof AuthenticatedAdminProductsRoute
    }
    '/_authenticated/admin/orders/$id': {
      id: '/_authenticated/admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AuthenticatedAdminOrdersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/inventory/import': {
      id: '/_authenticated/admin/inventory/import'
      path: '/import'
      fullPath: '/admin/inventory/import'
      preLoaderRoute: typeof AuthenticatedAdminInventoryImportRouteImport
      parentRoute: typeof AuthenticatedAdminInventoryRoute
    }
    '/_authenticated/admin/inventory/audit': {
      id: '/_authenticated/admin/inventory/audit'
      path: '/audit'
      fullPath: '/admin/inventory/audit'
      preLoaderRoute: typeof AuthenticatedAdminInventoryAuditRouteImport
      parentRoute: typeof AuthenticatedAdminInventoryRoute
    }
    '/_authenticated/admin/inventory/$id': {
      id: '/_authenticated/admin/inventory/$id'
      path: '/$id'
      fullPath: '/admin/inventory/$id'
      preLoaderRoute: typeof AuthenticatedAdminInventoryIdRouteImport
      parentRoute: typeof AuthenticatedAdminInventoryRoute
    }
  }
}

interface AuthenticatedAdminInventoryRouteChildren {
  AuthenticatedAdminInventoryIdRoute: typeof AuthenticatedAdminInventoryIdRoute
  AuthenticatedAdminInventoryAuditRoute: typeof AuthenticatedAdminInventoryAuditRoute
  AuthenticatedAdminInventoryImportRoute: typeof AuthenticatedAdminInventoryImportRoute
}

const AuthenticatedAdminInventoryRouteChildren: AuthenticatedAdminInventoryRouteChildren =
  {
    AuthenticatedAdminInventoryIdRoute: AuthenticatedAdminInventoryIdRoute,
    AuthenticatedAdminInventoryAuditRoute:
      AuthenticatedAdminInventoryAuditRoute,
    AuthenticatedAdminInventoryImportRoute:
      AuthenticatedAdminInventoryImportRoute,
  }

const AuthenticatedAdminInventoryRouteWithChildren =
  AuthenticatedAdminInventoryRoute._addFileChildren(
    AuthenticatedAdminInventoryRouteChildren,
  )

interface AuthenticatedAdminProductsRouteChildren {
  AuthenticatedAdminProductsIdRoute: typeof AuthenticatedAdminProductsIdRoute
  AuthenticatedAdminProductsIndexRoute: typeof AuthenticatedAdminProductsIndexRoute
}

const AuthenticatedAdminProductsRouteChildren: AuthenticatedAdminProductsRouteChildren =
  {
    AuthenticatedAdminProductsIdRoute: AuthenticatedAdminProductsIdRoute,
    AuthenticatedAdminProductsIndexRoute: AuthenticatedAdminProductsIndexRoute,
  }

const AuthenticatedAdminProductsRouteWithChildren =
  AuthenticatedAdminProductsRoute._addFileChildren(
    AuthenticatedAdminProductsRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminHomepageFeaturedRoute: typeof AuthenticatedAdminHomepageFeaturedRoute
  AuthenticatedAdminImageBackfillRoute: typeof AuthenticatedAdminImageBackfillRoute
  AuthenticatedAdminImageQualityPreviewRoute: typeof AuthenticatedAdminImageQualityPreviewRoute
  AuthenticatedAdminInventoryRoute: typeof AuthenticatedAdminInventoryRouteWithChildren
  AuthenticatedAdminPipeline_upscaleRoute: typeof AuthenticatedAdminPipeline_upscaleRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRouteWithChildren
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminScanRoute: typeof AuthenticatedAdminScanRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminOrdersIdRoute: typeof AuthenticatedAdminOrdersIdRoute
  AuthenticatedAdminOrdersIndexRoute: typeof AuthenticatedAdminOrdersIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
    AuthenticatedAdminHomepageFeaturedRoute:
      AuthenticatedAdminHomepageFeaturedRoute,
    AuthenticatedAdminImageBackfillRoute: AuthenticatedAdminImageBackfillRoute,
    AuthenticatedAdminImageQualityPreviewRoute:
      AuthenticatedAdminImageQualityPreviewRoute,
    AuthenticatedAdminInventoryRoute:
      AuthenticatedAdminInventoryRouteWithChildren,
    AuthenticatedAdminPipeline_upscaleRoute:
      AuthenticatedAdminPipeline_upscaleRoute,
    AuthenticatedAdminProductsRoute:
      AuthenticatedAdminProductsRouteWithChildren,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminScanRoute: AuthenticatedAdminScanRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminOrdersIdRoute: AuthenticatedAdminOrdersIdRoute,
    AuthenticatedAdminOrdersIndexRoute: AuthenticatedAdminOrdersIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAccountEditRoute: typeof AuthenticatedAccountEditRoute
  AuthenticatedAddressesRoute: typeof AuthenticatedAddressesRoute
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAccountEditRoute: AuthenticatedAccountEditRoute,
  AuthenticatedAddressesRoute: AuthenticatedAddressesRoute,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CatalogueRoute: CatalogueRoute,
  ContactRoute: ContactRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicAdminBulkLinkImagesRoute: ApiPublicAdminBulkLinkImagesRoute,
  CategorySlugSubRoute: CategorySlugSubRoute,
  CategorySlugIndexRoute: CategorySlugIndexRoute,
  ApiPublicHooksLowStockDigestRoute: ApiPublicHooksLowStockDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
